[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.94"
ascii = "1.1.0"
log = "0.4.22"
rand = "0.8.5"
shared = { path = "../shared" }
tiny_http = "0.12.0"
tungstenite = "0.24.0"
